import {
  Bike,
  BookOpen,
  Brain,
  Code,
  Coffee,
  Droplet,
  Dumbbell,
  Footprints,
  Heart,
  Languages,
  Leaf,
  type LucideIcon,
  Moon,
  Music,
  PenLine,
  Salad,
  Smartphone,
  Sprout,
  Sun,
  Target,
  Wallet,
} from 'lucide-react'

import type { HabitIcon } from '@/types'

/** The curated icon set users can pick from. One library, one stroke style. */
export const HABIT_ICON_COMPONENTS: Record<HabitIcon, LucideIcon> = {
  dumbbell: Dumbbell,
  salad: Salad,
  smartphone: Smartphone,
  'book-open': BookOpen,
  footprints: Footprints,
  bike: Bike,
  droplet: Droplet,
  moon: Moon,
  brain: Brain,
  heart: Heart,
  leaf: Leaf,
  sun: Sun,
  coffee: Coffee,
  'pen-line': PenLine,
  music: Music,
  languages: Languages,
  code: Code,
  wallet: Wallet,
  sprout: Sprout,
  target: Target,
}

export const HABIT_ICON_LABELS: Record<HabitIcon, string> = {
  dumbbell: 'Dumbbell',
  salad: 'Salad',
  smartphone: 'Phone',
  'book-open': 'Book',
  footprints: 'Steps',
  bike: 'Bike',
  droplet: 'Water',
  moon: 'Sleep',
  brain: 'Mind',
  heart: 'Heart',
  leaf: 'Leaf',
  sun: 'Sun',
  coffee: 'Coffee',
  'pen-line': 'Writing',
  music: 'Music',
  languages: 'Languages',
  code: 'Code',
  wallet: 'Money',
  sprout: 'Growth',
  target: 'Goal',
}
