import {
  Activity,
  Apple,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Camera,
  Carrot,
  CigaretteOff,
  Code,
  Coffee,
  Dog,
  Droplet,
  Dumbbell,
  Flower2,
  Footprints,
  GlassWater,
  GraduationCap,
  Guitar,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Languages,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Mic,
  Moon,
  Mountain,
  Music,
  Palette,
  PenLine,
  PersonStanding,
  Phone,
  Pill,
  Rocket,
  Salad,
  ShowerHead,
  Smartphone,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Target,
  Timer,
  TreePine,
  Trophy,
  Users,
  Wallet,
  Waves,
  Wind,
  WineOff,
} from 'lucide-react'

import type { HabitIcon } from '@/types'

/** The curated icon set users can pick from. One library, one stroke style. */
export const HABIT_ICON_COMPONENTS: Record<HabitIcon, LucideIcon> = {
  dumbbell: Dumbbell,
  salad: Salad,
  smartphone: Smartphone,
  'book-open': BookOpen,
  footprints: Footprints,
  bike: Bike,
  droplet: Droplet,
  moon: Moon,
  brain: Brain,
  heart: Heart,
  leaf: Leaf,
  sun: Sun,
  coffee: Coffee,
  'pen-line': PenLine,
  music: Music,
  languages: Languages,
  code: Code,
  wallet: Wallet,
  sprout: Sprout,
  target: Target,
  apple: Apple,
  carrot: Carrot,
  'glass-water': GlassWater,
  pill: Pill,
  bed: Bed,
  activity: Activity,
  'heart-pulse': HeartPulse,
  waves: Waves,
  'person-standing': PersonStanding,
  mountain: Mountain,
  'tree-pine': TreePine,
  flower: Flower2,
  sunrise: Sunrise,
  timer: Timer,
  wind: Wind,
  smile: Smile,
  sparkles: Sparkles,
  'shower-head': ShowerHead,
  'cigarette-off': CigaretteOff,
  'wine-off': WineOff,
  brush: Brush,
  palette: Palette,
  camera: Camera,
  guitar: Guitar,
  headphones: Headphones,
  mic: Mic,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  briefcase: Briefcase,
  users: Users,
  phone: Phone,
  dog: Dog,
  home: Home,
  trophy: Trophy,
  star: Star,
  rocket: Rocket,
}

export const HABIT_ICON_LABELS: Record<HabitIcon, string> = {
  dumbbell: 'Dumbbell',
  salad: 'Salad',
  smartphone: 'Phone',
  'book-open': 'Book',
  footprints: 'Steps',
  bike: 'Bike',
  droplet: 'Water',
  moon: 'Sleep',
  brain: 'Mind',
  heart: 'Heart',
  leaf: 'Leaf',
  sun: 'Sun',
  coffee: 'Coffee',
  'pen-line': 'Writing',
  music: 'Music',
  languages: 'Languages',
  code: 'Code',
  wallet: 'Money',
  sprout: 'Growth',
  target: 'Target',
  apple: 'Apple',
  carrot: 'Vegetables',
  'glass-water': 'Glass of water',
  pill: 'Vitamins',
  bed: 'Bed',
  activity: 'Activity',
  'heart-pulse': 'Cardio',
  waves: 'Swimming',
  'person-standing': 'Posture',
  mountain: 'Hiking',
  'tree-pine': 'Nature',
  flower: 'Flower',
  sunrise: 'Early rise',
  timer: 'Timer',
  wind: 'Breathing',
  smile: 'Mood',
  sparkles: 'Self-care',
  'shower-head': 'Cold shower',
  'cigarette-off': 'No smoking',
  'wine-off': 'No alcohol',
  brush: 'Art',
  palette: 'Painting',
  camera: 'Photo',
  guitar: 'Guitar',
  headphones: 'Listening',
  mic: 'Singing',
  'graduation-cap': 'Study',
  lightbulb: 'Ideas',
  briefcase: 'Work',
  users: 'Friends',
  phone: 'Call family',
  dog: 'Dog walk',
  home: 'Home',
  trophy: 'Goal',
  star: 'Star',
  rocket: 'Project',
}
